# Generated by Django 2.1.3 on 2018-12-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bayar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bayar'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
