# Generated by Django 2.1.3 on 2018-12-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20181213_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='QTY'),
        ),
    ]
