# Generated by Django 2.1.3 on 2018-12-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20181214_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='cart',
            name='kembali',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kembali'),
        ),
    ]
