# Generated by Django 2.1.3 on 2018-12-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20181214_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='resi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resi'),
        ),
    ]
