# Generated by Django 2.1.3 on 2018-12-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
