# Generated by Django 2.1.3 on 2018-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_telp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alamat',
            field=models.TextField(blank=True, null=True, verbose_name='alamat'),
        ),
    ]
